# -*- coding: utf-8 -*-
"""Sorveteria.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a_DXoHtuHTRbg6G1QyLbJYORi2KZw3ht

#Código da Loja de sorvete
"""

#Sorveteria
print('Bem-vindo a Sorveteria do Eduardo')
print('-----------------------------------Cardápio---------------------------------------') #Cardápio
print('| N de bolas | Sabor Tradicional (tr) | Sabor Premium (pr) | Sabor Especial (es) |')
print('|     1      |         R$6,00         |       R$7,00       |        R$8,00       |')
print('|     2      |         R$10,00        |       R$12,00      |        R$14,00      |')
print('|     3      |         R$14,00        |       R$17,00      |        R$20,00      |')
print('----------------------------------------------------------------------------------')

acumulador = 0
while True:
 sabor =input('Entre com o sabor desejado (tr/es/pr):')
 if sabor != 'tr' and sabor != 'es' and sabor != 'pr':
  print('Sabor inválido.Tente novamente')
  continue

 num_bolas = input('Entre com o número de bolas de sorvete desejado (1,2,3): ')
 if num_bolas != '1' and num_bolas != '2' and num_bolas != '3':
  print('Número de bolas de sorvete inválido.Tente novamente')
  continue

 if num_bolas == '1' and sabor == 'tr':
    acumulador = acumulador + 6
    print('Você pediu 1 bola de sorvete no sabor TRADICIONAL: R$6,00')

 elif num_bolas == '2' and sabor == 'tr':
    acumulador = acumulador + 10
    print('Você pediu 2 bolas de sorvete no sabor TRADICIONAL: R$10,00')

 elif num_bolas == '3' and sabor == 'tr':
    acumulador = acumulador + 14
    print('Você pediu 3 bolas de sorvete no sabor TRADICIONAL: R$14,00')

 elif num_bolas == '1' and sabor == 'pr':
    acumulador = acumulador + 7
    print('Você pediu 1 bola de sorvete no sabor PREMIUM: R$7,00')

 elif num_bolas == '2' and sabor == 'pr':
    acumulador = acumulador + 12
    print('Você pediu 2 bolas de sorvete no sabor PREMIUM: R$12,00')

 elif num_bolas == '3' and sabor == 'pr':
    acumulador = acumulador + 17
    print('Você pediu 3 bolas de sorvete no sabor PREMIUM: R$17,00')

 elif num_bolas == '1' and sabor == 'es':
    acumulador = acumulador + 8
    print('Você pediu 1 bola de sorvete no sabor ESPECIAL: R$8,00')

 elif num_bolas == '2' and sabor == 'es':
    acumulador = acumulador + 14
    print('Você pediu 2 bolas de sorvete no sabor ESPECIAL: R$14,00')

 elif num_bolas == '3' and sabor == 'es':
    acumulador = acumulador + 20
    print('Você pediu 3 bolas de sorvete no sabor ESPECIAL: R$20,00')

 mais_sorvete = input('Deseja mais algum sorvete (S/digite outra tecla)?:')#Opção de mais algum sorvete
 mais_sorvete = mais_sorvete.upper()#Aceitar o s pois o que for digitado vai ficar maiúsculo

 if mais_sorvete == 'S':
  continue
 else:
    print('O valor total a ser pago: R${:.2f}'.format(acumulador)) #Valor total(Resultado de todo o acumulador)
    break #Encerrar o laço de repetição e o programa